// Problem 2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibList = [1, 2];
let x = 0;
let y = 1;
let z = 0;
let evenFibTotal = 2;

while (z < 4000000) {
    z = fibList[x] + fibList[y];
    console.log(z);

    x++;
    y++;

    // fibList[0] = fibList[1];
    // console.log(fibList);

    // fibList[1] = z;
    // console.log(fibList);

    fibList.push(z);
    console.log(fibList);

    if (z % 2 == 0) {
        evenFibTotal += z;
    }

    console.log(evenFibTotal);
}
